spring.application.name=trivia
spring.datasource.url=jdbc:postgresql://localhost:5432/TriviaGame
spring.datasource.username=postgres
# Criar variável de ambiente para senha do banco de dados e referenciar aqui!
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl